name: 'Get and cache deps'
description: 'get deps and cache them'
inputs:
  caching:
    description: 'to cache or to cache not'
    required: false
    default: 'true'
    type: string
outputs:
  used-cache:
    description: 'the cache was used'
    value: ${{steps.install_deps.outputs.cache}}
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install_deps
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: |
        npm ci
        echo "cache='${{inputs.caching}}'" >> $GITHUB_OUTPUT
      shell: bash
